sudo: required
services:
  - docker


before_install:
  - docker build  -t anreddy/django-polls -f Dockerfile.dev
  - docker run --rm  -it  amazon/aws-cli --version
  - docker run --rm   amazon/aws-cli s3 ls


script:
  - docker run anreddy/django-polls python3 ./mysite/manage.py test run
after_success:
  - docker build -t anreddy/django-polls -f Dockerfile.dev
  # Login to Docker cli
  - echo "$DOCKER_PASSWORD"|docker login -u "$DOCKER_ID" --password-stdin
    # Push images to docker hub.
  - docker push anreddy/django-polls


