sudo: required
services:
  - docker

before_install:
  #- docker build  -t anreddy/django-polls -f Dockerfile.dev .
   - docker build  -t anreddy/polls_sqlite -f Dockerfile.dev_aws .
   - docker build -t anreddy/nginx-image -f Nginx/Dockerfile.nginx .

script:
 #- docker run anreddy/django-polls python3 ./mysite/manage.py test run
  - docker run anreddy/polls_sqlite python3 ./mysite/manage.py test run

after_success:
   #- docker build  -t anreddy/django-polls -f Dockerfile.dev .
   - docker build  -t anreddy/polls_sqlite -f Dockerfile.dev_aws .
   - docker build -t anreddy/nginx-image -f Nginx/Dockerfile.nginx .
   #Login to Docker cli
   - echo "$DOCKER_PASSWORD"|docker login -u "$DOCKER_ID" --password-stdin
   # Push images to docker hub.
   #- docker push anreddy/django-polls
   - docker push anreddy/polls_sqlite
   - docker push anreddy/nginx-image

#deploy:
 # provider: elasticbeanstalk
  #region: "us-east-1"
  #app: "django-polls"
  #env: "djangopolls-env"
  #bucket_name: "elasticbeanstalk-us-east-1-298693496319"
  #bucket_path: "django-polls"
  #on:
   # branch: feature
  #access_key_id: $Aws_Access_key
  #secret_access_key: $Aws_Secret_Key




