sudo: required
services:
  - docker

before_install:
  - docker build  -t anreddy/django-polls .

script:
 - docker run anreddy/django-polls python3 ./mysite/manage.py test run

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "django-polls"
  env: "djangopolls-env"
  bucket_name: "elasticbeanstalk-us-east-1-298693496319"
  bucket_path: "django-polls"
  on:
    branch: master
  access_key_id: $Aws_Access_key
  secret_access_key: $Aws_Secret_Key




