apiVersion: apps/v1
kind: Deployment
metadata:
  name: polls-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: polls-container
          image: anreddy/django-polls
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_HOST
              value: postgres-db-cluster-ip-service
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DATABASE
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: POSTGRES_PASSWORD












